simplify sleep_inhibbitor, inhibit only during zenity_emerge functions and standard upgrade

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -64,50 +64,43 @@ set_param () {
 
 # Function to inhibit sleep mode
 ## USAGE: sleep_inhibitor [OPTION]
-## OPTION:	get/?: check if inhibitor avalaible (Xfce) & return result
-##			off/0 or on/1 
+## OPTION:	off/0 or on/1 (default)
 sleep_inhibitor () {
-	local inhibit=true
+	local inhibit=false
 	if [ $# -gt 0 ]; then
 		case "$1" in
-		 'get'|'?')
+		 'off'|0)
+		 	;;
+		 *)
+		 	# First check if inhibition is available
 		 	case $XDG_CURRENT_DESKTOP in
 		 	 *XFCE*)
-		 		inhibit=$( su $USER -c 'xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode' ) || return 255
+		 		inhibit=$( su $USER -c 'xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode' ) || return 2
 		 		;;
-		 	 *GNOME*)
-		 	 	return 1
-		 	 	;;
-		 	 *KDE*)
-		 	 	return 1
-		 	 	;;
 		 	 *)
 		 	 	return 1
 		 	 	;;
 		 	esac
-		 	[ $inhibit == true ] && return 1 || return 0
-		 	;;
-		 'off'|0)
-		 	inhibit=false
-		 	;;
-		 *)
 		 	;;
 		esac
 	fi
 	
+	# Verbose mode
 	if [ ! $QUIET ] || [ $VERBOSE ]; then
 		[ $inhibit == true ] && echo $"Inhibiting sleep mode" || echo $"Reactivating sleep mode"
 	fi
+	# Inhibit oor uninhibit, delete local var on error
  	case $XDG_CURRENT_DESKTOP in
  	 *XFCE*)
-		su $USER -c "xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s $inhibit" || return 1
+		su $USER -c "xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s $inhibit" || unset inhibit
 		;;
 	 *)
 	 	return 1
 	 	;;
 	esac
-	[ $inhibit == true ] && set_param 'inhibited' 1 || set_param 'inhibited' 0
-	return 0
+	# check status, set global parameter & return
+	[ $inhibit ] && [ $inhibit == true ] && set_param 'inhibited' 1 || set_param 'inhibited' 0
+	[ $inhibit ] && return 0 || return 3
 }
 
 # Function to get last log line
@@ -311,6 +304,7 @@ zenity_emerge() {
 	# clean tmp files
 	prepare_for_exit
 	
+	# Prepare parameters
 	case $1 in
 	 -s|--sync)
 	 	local ACTION='sync'
@@ -449,6 +443,10 @@ zenity_emerge() {
 		;;
 	esac
 
+	# Inhibit sleep mode if possible
+	sleep_inhibitor
+	
+	# Launch emerge function in background
 	echo -e "${green}${title}...${nocolor}"
 	(
 		case $ACTION in
@@ -512,7 +510,8 @@ zenity_emerge() {
 	exFuncs=( ${exFuncs[@]} $! )
 	sleep .5
 	dots=""
-		
+	
+	# Show zenity window while process exists
 	while [ ! -f "${tmpFile[result]}" ]; do
 		sleep $slp
 		
@@ -631,6 +630,9 @@ zenity_emerge() {
 		prepare_for_exit ${exFuncs[@]}
 		mv "/tmp/log.bak" "${tmpFile[logs]}"
 	fi
+	
+	# Restore initial sleep mode status
+	[ $INHIBITED ] && sleep_inhibitor off
 
 	# Print messages from emerging
 	# $message is a table of a new messages line
@@ -1194,10 +1196,6 @@ fi
 
 # Sync
 if [ $SYNC ]; then
-	# Check if sleep mode can be inhibited and inhibit if possible
-	sleep_inhibitor ?
-	[ $? -eq 0 ] && sleep_inhibitor
-	
 	if [ ! $GTK ]; then
 		title=$"Syncing repositories"
 		echo -e "${green}${title}...${nocolor}"
@@ -1215,9 +1213,6 @@ if [ $SYNC ]; then
 		else set_param 'portage' 0
 		fi
 	fi
-	
-	# restore initial sleep mode status
-	[ $INHIBITED ] && sleep_inhibitor off
 else 
 	eix -qu sys-apps/portage && set_param 'portage' 1 || set_param 'portage' 0
 fi
@@ -1268,9 +1263,8 @@ if [ $GTK ]; then
 
 	# update portage?
 	if [ $UPDATE_PORTAGE ]; then
-		# Check if sleep mode can be inhibited and inhibit if possible
-		sleep_inhibitor ?
-		[ $? -eq 0 ] && sleep_inhibitor
+		# Inhibit sleep mode if possible
+		sleep_inhibitor
 		
 		zenity_upgrade sys-apps/portage
 		[ $? -gt 10 ] && final_exit $(( $?-10 ))
@@ -1280,10 +1274,6 @@ if [ $GTK ]; then
 	fi
 
 	# upgrade
-	# Check if sleep mode can be inhibited and inhibit if possible
-	sleep_inhibitor ?
-	[ $? -eq 0 ] && sleep_inhibitor
-	
 	zenity_upgrade ${SET}
 	case $? in
 	 0) # all done
@@ -1306,14 +1296,10 @@ if [ $GTK ]; then
 	 	;;
 	esac
 	
-	# restore initial sleep mode status
-	[ $INHIBITED ] && sleep_inhibitor off
-		
 # Standard upgrade
 else
-	# Check if sleep mode can be inhibited and inhibit if possible
-	sleep_inhibitor ?
-	[ $? -eq 0 ] && sleep_inhibitor
+	# Inhibit sleep mode if possible
+	sleep_inhibitor
 	
 	text=$"Checking for upgrades"
 	echo -e "${green}${text}...${nocolor}"
@@ -1332,10 +1318,6 @@ fi
 
 # Depclean
 if [ -z "$exclude" ] && [ "$SET" = "@world" ]; then
-	# Check if sleep mode can be inhibited and inhibit if possible
-	sleep_inhibitor ?
-	[ $? -eq 0 ] && sleep_inhibitor
-	
 	if [ $GTK ]; then
 		zenity_upgrade --depclean
 		case $? in
@@ -1357,8 +1339,6 @@ if [ -z "$exclude" ] && [ "$SET" = "@world" ]; then
 		emerge -a${QUIET}${VERBOSE}c || final_exit 5
 	fi
 
-	# restore initial sleep mode status
-	[ $INHIBITED ] && sleep_inhibitor off
 fi
 
 # Finished
