translating

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -2,8 +2,9 @@
 # Script to sync && upgrade Gentoo portage
 version="1.04-r4"; script_name=`basename "$0"`
 
-TEXTDOMAINDIR=/home/anard/Applications/upgrade-portage/locale   # probably not the best place for these files, but OK for testing
 TEXTDOMAIN=upgrade
+#TEXTDOMAINDIR=/usr/share/locale
+TEXTDOMAINDIR=/home/anard/Applications/upgrade-portage/locale   # for testing
 
 configPath="/usr/lib"
 if [ -f "${configPath}/shell-text.cnf" ]; then
@@ -49,17 +50,12 @@ set_param () {
 	 	;;
 
 	 *)
-		echo -e "${red}${_set_param['param-error']}${nocolor}"
+	 	local mess=$"An error occurred while setting parameters"
+		echo -e "${red}${mess}${nocolor}"
 		return 1
 		;;
 	esac
 	return 0
-}
-
-# Function to print translated messages
-## USAGE : print_message MESSAGE
-print_message () {
-	eval echo $( echo "$@" | sed "s/\*\([^*]*\)\*/$\{\1\}/g" )
 }
 
 # Function to get last log line
@@ -135,7 +131,8 @@ prepare_for_exit () {
 		 	;;
 		esac
 
-		echo -e "${orange}$( print_message ${_prepare_for_exit[canceled]} )${nocolor}"
+		local mess=$"Cancelled ${func}"
+		echo -e "${orange}${mess}${nocolor}"
 	done
 	# delete tmp files
 	for file in ${tmpFile[@]}; do
@@ -149,7 +146,7 @@ prepare_for_exit () {
 ## array must have been declared via -A option and have name different than 'array'
 get_human_time () {
 	if [ $# -eq 0 ]; then
-		echo "$( print_message ${_generic[invalid-call]} )"
+		echo $"Invalid call to function ${FUNCNAME[0]}"
 		return 1
 	fi
 				
@@ -160,7 +157,7 @@ get_human_time () {
 	fi
 	
 	if [ $# -lt 2 ]; then
-		echo "$( print_message ${_generic[invalid-parameter]} )"
+		echo $"Invalid parameter $1 for function ${FUNCNAME[0]}"
 		return 1
 	fi
 	
@@ -202,7 +199,7 @@ get_human_time () {
 ## USAGE: print_human_time human_time
 print_human_time () {
 	if [ ! $# -eq 1 ] || [ $1 -eq $1 ] &>/dev/null; then
-		echo "$( print_message ${_generic[invalid-parameter]} )"
+		echo $"Invalid parameter for function ${FUNCNAME[0]}"
 		return 1
 	fi
 	
@@ -255,25 +252,25 @@ zenity_emerge() {
 	 -s|--sync)
 	 	local ACTION='sync'
 	 	local options="--pulsate"
-	 	local title=$( gettext "Syncing repositories" )
+	 	local title=$"Syncing repositories"
 	 	local slp=.5
 	 	local exFuncs=( rsync emerge )
-	 	local exText="$( print_message ${_zenity_emerge[sync-error]} )"
+	 	local exText=$"An error occurred while syncing, please check logs"
 	 	local exCode=2
 	 	;;
 	 -C|--check-depclean)
 	 	local ACTION='check-depclean'
-	 	local title="$( print_message ${_zenity_emerge[checkdep-title]} )"
+	 	local title=$"Preparing for cleaning"
 	 	local options="--pulsate"
 	 	local slp=.5
 		local exFuncs=( emerge )
-	 	local exText="$( print_message ${_zenity_emerge[checkdep-error]} )"
+	 	local exText=$"An error occurred while checking for obsolete packages, please check logs"
 	 	local exCode=5
 	 	;;
 	 -c|--depclean)
 	 	shift
 	 	local ACTION='depclean'
-	 	local title="$( print_message ${_zenity_emerge[depclean-title]} )"
+	 	local title=$"Cleaning your system"
 	 	local slp=.5
 	 	local shift
 	 	local options=""; excluded=""
@@ -283,7 +280,7 @@ zenity_emerge() {
 	 	 	 	local excluded="$2"
 	 	 		;;
 	 	 	 *)
-	 	 	 	echo "$( print_message ${_generic[invalid-param]} )"
+	 	 	 	echo $"Invalid parameter $1 for function ${FUNCNAME[0]}"
 	 	 	 	exit 255
 	 	 	 	;;
 	 	 	esac
@@ -294,7 +291,7 @@ zenity_emerge() {
 	 	local cleaning=0
 	 	local percent=0
 	 	local exFuncs=( emerge )
-	 	local exText="$( print_message ${_zenity_emerge[depclean-error]} )"
+	 	local exText=$"An error occurred while cleaning system, please check logs"
 	 	local exCode=6
 		;;
 	 -k|--check)
@@ -303,16 +300,16 @@ zenity_emerge() {
 	 	local UP=$2
 		case $UP in
 		 @*)
-		 	title=$"Checking for upgrades ${UP}"
+		 	title=$"Checking for upgrades"
 		 	;;
 		 *)
-		 	title="$( print_message ${_zenity_emerge[check-title2]} )"
+		 	title=$"Checking for ${UP} upgrade"
 		 	;;
 		esac
 		local options="--pulsate"
 		local slp=.5
 	 	local exFuncs=( emerge )
-	 	local exText="$( print_message ${_zenity_emerge[check-error]} )"
+	 	local exText=$"An error occurred while checking dependencies, please check logs"
 	 	local exCode=3
 	 	;;
 	 	
@@ -322,14 +319,14 @@ zenity_emerge() {
 	 	local UP=$1
 		case $UP in
 		 "@world")
-			local title="$( print_message ${_zenity_emerge[upgrade-title1]} )"
+			local title=$"Upgrading your system"
 			;;
 		 @*)
-			local title="$( print_message ${_zenity_emerge[upgrade-title2]} )"
+			local title=$"Upgrading ${UP}"
 			;;
 		 *)
 		 	local pack=${UP#*/}
-		 	local title="$( print_message ${_zenity_emerge[upgrade-title1]} )"
+		 	local title=$"Upgrading ${pack^}"
 			;;
 		esac
 		local slp=1
@@ -347,7 +344,7 @@ zenity_emerge() {
 	 	 	 	excluded="$2"
 	 	 		;;
 	 	 	 *)
-	 	 	 	echo "$( print_message ${_generic[invalid-param]} )"
+	 	 	 	echo $"Invalid parameter $1 for function ${FUNCNAME[0]}"
 	 	 	 	exit 255
 	 	 	 	;;
 	 		esac
@@ -382,7 +379,7 @@ zenity_emerge() {
 		local percent=0; local elapsed=0;
 		declare -A elapsed_h=( [machine]=0 [d]=0 [h]=0 [m]=0 [s]=0 )
 	 	local exFuncs=( emerge )
-	 	local exText="$( print_message ${_zenity_emerge[upgrade-error]} )"
+	 	local exText=$"An error occurred while upgrading system, please check logs"
 	 	local exCode=4
 		;;
 	esac
@@ -394,7 +391,8 @@ zenity_emerge() {
 			emerge --sync |& tee "${tmpFile["logs"]}"
 			res=$?
 			if [ $res -eq 0 ] && type eix &> /dev/null; then
-				echo -e "${green}$( print_message ${_zenity_emerge['eix-message']} ) ...${nocolor}"
+				local eix-mess=$"Updating eix database"
+				echo -e "${green}${eix-mess} ...${nocolor}"
 				eix-update & pid=$!
 				exFuncs[ $(( ${#exFuncs[@]}-1 )) ]=$pid
 				wait $pid
@@ -445,12 +443,13 @@ zenity_emerge() {
 		case $ACTION in
 		 'sync')
 		 	if pgrep eix-update &>/dev/null; then
-		 		echo "# $( print_message ${_zenity_emerge['eix-message']} )"
+		 		echo "# ${eix-mess}"
 		 	else print_line
 		 	fi
 		 	;;
 		 'check-depclean')
-		 	echo "# $( print_message ${_zenity_emerge['checkdep-message']} ) ${dots}"
+		 	local mess=$"Checking for obsolete packages"
+		 	echo "# ${mess} ${dots}"
 		 	[ "$dots" = "..." ] && dots="" || dots="${dots}."
 		 	;;
 		 	
@@ -467,7 +466,8 @@ zenity_emerge() {
 		 	;;
 		 	
 		 'check')
-		 	echo "# $( print_message ${_zenity_emerge['check-message']} ) ${dots}"
+		 	local mess=$"Calculating dependencies"
+		 	echo "# ${mess} ${dots}"
 		 	[ "$dots" = "..." ] && dots="" || dots="${dots}."
 		 	;;
 		 	
@@ -526,7 +526,8 @@ zenity_emerge() {
 				else echo " - ${print}"
 				fi
 			else
-				echo "# $( print_message ${_zenity_emerge['check-message']} ) ${dots}"
+				local mess="Calculating dependencies"
+				echo "# ${mess} ${dots}"
 				[ "$dots" = "..." ] && dots="" || dots="${dots}."
 			fi
 			
@@ -552,12 +553,12 @@ zenity_emerge() {
 		mess=$( sed -n "${message[$i]}p" "${tmpFile["logs"]}" )
 		case "${mess# * }" in
 		 IMPORTANT:*)
-			title="${_zenity_emerge['conf-title']}"
+			title=$"Configuration file needs update"
 			start=$(( ${message[$i]} ))
 			;;
 		 *)
 			package=$( sed -n "${message[$i]} s/^.*package \(.*\):$/\1/p" "${tmpFile["logs"]}" )
-			title="$( print_message ${_zenity_emerge['package-title']} )"
+			title=$"Messages for ${package}"
 			start=$(( ${message[$i]}+1 ))
 			;;
 		esac
@@ -614,14 +615,15 @@ zenity_upgrade () {
 			unset check
 		# Needs editing /etc/portage/
 		elif grep -q '^!!!' "${tmpFile["logs"]}"; then
-			remove_blanks "${tmpFile["logs"]}" | zenity --width ${WIDTH} --height ${HEIGHT} --window-icon "${iconPath}" --text-info --title "$( print_message ${_zenity_upgrade['conf-needed']} )"
+			remove_blanks "${tmpFile["logs"]}" | zenity --width ${WIDTH} --height ${HEIGHT} --window-icon "${iconPath}" --text-info --title $"Some configuration is necessary to proceed"
 			[ $? -gt 0 ] && prepare_for_exit && return 11
 			
 		else unset check		
 		fi
 	done
 	
-	local text="$( print_message ${_zenity_upgrade['uncheck-message']} )\n"
+	local text=$"Uncheck packages you want to exclude."
+	text+="\n"
 	case $ACTION in
 	 'depclean')
 		local title="unmerged"
@@ -666,11 +668,11 @@ zenity_upgrade () {
 			time_h[$i]=""
 		done
 		if [ ${#nomerge_action[@]} -gt 0 ]; then
-			[ ${#nomerge_action[@]} -gt 1 ] && plur="${_generic['pluriel']}" || plur=""
-			text+="\n${_zenity_upgrade['not-installed']}\n"
+			[ ${#nomerge_action[@]} -gt 1 ] && plur="s" || plur=""
+			text+="\n"; text+=$"Some package${plur} won't be installed :"; text+="\n"
 			for i in ${!nomerge_action[@]}; do
 				nomerge[$i]=$( sed '/^\[ebuild/d' "${tmpFile["logs"]}" | sed -n "$(( $i+1 ))p" | cut -d] -f2- )
-				text+="<span color=\"brown\">$( print_message ${nomerge_action[$i]} )</span> : ${nomerge[$i]}\n"
+				text+="<span color=\"brown\">${nomerge_action[$i]}</span> : ${nomerge[$i]}\n"
 			done
 		fi
 
@@ -679,13 +681,14 @@ zenity_upgrade () {
 		local totTime=0
 		if [ $ESTIMATE ]; then
 			# estimate each time
-			echo -e "${green}$( print_message ${_zenity_upgrade['est-merge']} )...${nocolor}"
+			local mess=$"Estimating merge time"
+			echo -e "${green}${mess}...${nocolor}"
 			for i in ${!list[@]}; do
 				time[$i]=$( get_av_merge "${package[$i]}" )
 				if [ -z ${time[$i]} ]; then
 					time[$i]=0
 					time_h[$i]='??:??'
-					echo "$( print_message ${_zenity_upgrade['est-not-found']} )"
+					echo $"Unknown merge time for ${package[$i]}"
 				else
 					let nb+=1
 					let totTime+=${time[$i]}
@@ -693,7 +696,7 @@ zenity_upgrade () {
 					get_human_time time_hum ${time[$i]}
 					time_h[$i]=$( print_human_time time_hum )
 					unset time_hum
-					echo "$( print_message ${_zenity_upgrade['est-found']} )"
+					echo $"Average merge time for ${package[$i]} is ${time_h[$i]}"
 				fi
 			done
 		fi
@@ -702,7 +705,8 @@ zenity_upgrade () {
 		if [ $nb -eq ${#list[@]} ]; then
 			declare -A time_hum
 			get_human_time time_hum $totTime
-			text+="$( print_message ${_zenity_upgrade['est-total']} ) $( print_human_time time_hum ).\n"
+			text+=$"Estimated merge time is"
+			text+=" $( print_human_time time_hum ).\n"
 			unset time_hum
 		fi
 		
@@ -715,7 +719,7 @@ zenity_upgrade () {
 			aborted=1
 			;;
 		 *)
-		 	text="$( print_message ${_zenity_upgrade['package-message']} )\n"
+		 	text=$"${UP} needs update, it's highly recommended to do it first.\n"
 		 	check=""
 			[ $ESTIMATE ] || options+=" --hide-column 5"		 	
 			aborted=11
@@ -730,8 +734,8 @@ zenity_upgrade () {
 		;;
 	esac	
 	
-	[ $number -gt 1 ] && plur="${_generic["pluriel"]}" || plur=""
-	[ $ACTION = 'upgrade' ] && title="$( print_message ${_zenity_upgrade['merge-title']} )" || title="$( print_message ${_zenity_upgrade['unmerge-title']} )"
+	[ $number -gt 1 ] && plur="s" || plur=""
+	[ $ACTION = 'upgrade' ] && title=$"${number} package${plur} should be merged" || title=$"${number} package${plur} should be unmerged"
 	
 	choice=( $(
 		for i in ${!package[@]}; do
@@ -744,7 +748,8 @@ zenity_upgrade () {
 		[ "${UP:0:1}" = '@' ] || choice=( ${package[@]} )
 	fi
 	if [ "$ret" -gt 0 ] || [ ${#choice[@]} -eq 0 ]; then
-		echo -e "${orange}$( print_message ${_generic['abort']} )${nocolor}"
+		local mess=$"Aborted"
+		echo -e "${orange}${mess}${nocolor}"
 		prepare_for_exit
 		if [ "$ACTION" = "upgrade" ] && [ "${UP:0:1}" = '@' ]; then
 			return 11
@@ -860,7 +865,7 @@ HELP
 		;;
 
 	 *)
-		echo -e "${red}Unknown parameter ${1}${nocolor}, exiting..." && exit 255
+		echo -e $"${red}Unknown parameter ${1}${nocolor}, exiting..." && exit 255
 		;;
 	esac
 	shift
@@ -877,7 +882,8 @@ repos=( $( grep location /etc/portage/repos.conf/* | cut -d '=' -f2 ) )
 
 # Search for last sync timestamps
 last=0
-text="Checking repositories..."
+text=$"Checking repositories"
+text+="..."
 echo -e "${green}${text}${nocolor}"
 unset time
 for i in "${!repos[@]}"; do
@@ -888,15 +894,15 @@ for i in "${!repos[@]}"; do
 		[ ! $QUIET ] || [ $VERBOSE ] && echo "${text}"
 
 		if [ ${time[$i]} -gt `date '+%s'` ]; then
-			text1="Sync date for ${repos[$i]##*/} is newer than now"
-			text2=", please correct your local time"
+			text1=$"Sync date for ${repos[$i]##*/} is newer than now"
+			text2=$", please correct your local time"
 			[ ! $GTK ] && echo -e "${red}${text1}${nocolor}${text2}" || zenity --width ${WIDTH} --window-icon "${iconPath}" --error --title "Time error" --text "<span color=\"red\">${text1}</span>${text2}"
-			echo "Exiting..."
+			echo $"Exiting..."
 			exit 1
 		fi
 
 	else
-		text="Unknown last sync for ${repos[$i]##*/}"
+		text=$"Unknown last sync for ${repos[$i]##*/}"
 		[ $VERBOSE ] && echo "${text}"
 	fi
 done
@@ -912,16 +918,19 @@ now=$(date "+%s")
 # less than 1 day
 if [ $now -lt $last ]; then
 
-	text1="Your last sync is newer than 1 day"
-	text2="Do you want to sync again ?"
-	text3="-->" 
+	text1=$"Your last sync is newer than 1 day"
+	text2=$"Do you want to sync again ?"
+	text3="-->"
+	answerok=$"y"
+	answerko=$"n"
+	answers="(${answerok}/${answerko^})"
 
 	if [ $GTK ]; then
 		if ! zenity --width ${WIDTH} --window-icon "${iconPath}" --question --title "${text1}" --text "${text2}" --default-cancel; then
 			set_param 'sync' 0
 		fi
 	else
-		echo "${bold}${text1}${normal}. ${text2} (y/N)"
+		echo "${bold}${text1}${normal}. ${text2} ${answers}"
 		while true;	do
 
 			read -p "${text3}" ans
@@ -937,25 +946,26 @@ if [ $now -lt $last ]; then
 					;;
 
 				*)
-					echo "Unknown answer (y/N ?)"
+					echo -n $"Unknown answer"
+					echo " (${answerok}/${answerko^} ?)"
 					;;
-
 			esac
 		done
 	fi
-	text="Last sync newer than 24h, "
-	[ $SYNC ] && echo "${text}forcing sync" || echo "${text}skipping sync"
+	text1=$"Last sync newer than 24h"
+	[ $SYNC ] && echo text2=$"forcing sync" || text2=$"skipping sync"
+	echo "${text1}, ${text2}"
 fi
 
 # Sync
 if [ $SYNC ]; then
 	if [ ! $GTK ]; then
-		title="Syncing repositories"
+		title=$"Syncing repositories"
 		echo -e "${green}${title}...${nocolor}"
 		emerge --sync
 		[ $? -gt 0 ] && exit 2
 		if type eix &> /dev/null; then
-			echo "Updating eix database"
+			echo $"Updating eix database"
 			eix-update
 		fi
 	else
@@ -991,7 +1001,7 @@ if [ $GTK ]; then
 		choice=( $(
 			for i in ${!index[@]}; do
 				echo -e "TRUE\n${index[$i]}\n${title[$i]}\n${date[$i]}"
-			done | zenity --width ${WIDTH} --height ${HEIGHT} --window-icon "${iconPath}" --list --checklist --column 'read' --column 'index' --column 'Title' --column 'Date' --hide-column 2 --separator ' ' --title "${#index[@]} news need reading" --text "Keep checked those you want to read now" ) )
+			done | zenity --width ${WIDTH} --height ${HEIGHT} --window-icon "${iconPath}" --list --checklist --column 'read' --column 'index' --column 'Title' --column 'Date' --hide-column 2 --separator ' ' --title $"${#index[@]} news need reading" --text $"Keep checked those you want to read now" ) )
 
 		for i in ${!choice[@]}; do
 			eselect news read ${choice[$i]} | zenity --width ${WIDTH} --height ${HEIGHT} --window-icon "${iconPath}" --text-info --title "${title[$i]}"
@@ -1014,8 +1024,8 @@ if [ $GTK ]; then
 	 	set_param 'upgrade' 0
 	 	;;
 	 2) # partial
-		text="Partial upgrade is done"
-		zenity --width ${WIDTH} --window-icon "${iconPath}" --info --title "Upgrade" --text "${text}"
+		text=$"Partial upgrade is done"
+		zenity --width ${WIDTH} --window-icon "${iconPath}" --info --title $"Upgrade" --text "${text}"
 		exit 0
 	 	;;
 	 3) # preserved libs
@@ -1029,13 +1039,13 @@ if [ $GTK ]; then
 		
 # Standard upgrade
 else
-	text="Checking for upgrades"
+	text=$"Checking for upgrades"
 	echo -e "${green}${text}...${nocolor}"
 	emerge -a${QUIET}${VERBOSE}uDN ${SET}
 
 	if [ $? -gt 0 ]; then
-		text1="An error occurred on compilation time"
-		text2="please check logs for more information"
+		text1=$"An error occurred on compilation time"
+		text2=$"please check logs for more information"
 		echo -e "${red}${text1}${nocolor}, ${text2}"
 		exit 4
 	fi
@@ -1060,14 +1070,14 @@ if [ -z "$exclude" ] && [ "$SET" = "@world" ]; then
 
 	# Standard cleaning
 	else
-		text="Cleaning your system"
+		text=$"Cleaning your system"
 		echo -e "${green}${text}...${nocolor}"
 		emerge -a${QUIET}${VERBOSE}c || exit 5
 	fi
 fi
 
 # Finished
-[ $UPGRADE_NEEDED ] && text="Your system is now up to date" || text="Your system was already up to date"
+[ $UPGRADE_NEEDED ] && text=$"Your system is now up to date" || text=$"Your system was already up to date"
 [ $GTK ] && zenity --width ${WIDTH} --window-icon "${iconPath}" --info --title "Upgrade" --text "${text}" && prepare_for_exit
 echo "${text}"
 
