resolved bug

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -4,7 +4,6 @@ configPath="/usr/lib"
 if [ -f "${configPath}/shell-text.cnf" ]; then
 	source "${configPath}/shell-text.cnf"
 fi
-logFile="/var/log/upgrade.log"
 declare -A tmpFile=( ['logs']="/tmp/upgrade-portage.log" ['zenity']="/tmp/zenity-progress.log" )
 
 # Functions
@@ -51,7 +50,7 @@ prepare_for_exit () {
 
 	# kill launched function
 	for i in "${!functions[@]}"; do
-		echo "Canceled ${functions[$i]}" >> "${logFile}"
+		echo "Canceled ${functions[$i]}"
 		pkill "${functions[$i]}"
 	done
 	# delete tmp files
@@ -118,33 +117,30 @@ HELP
 done
 
 # Get repos locations
-echo >> "${logFile}"
-echo "### $(date) ###" >> "${logFile}"
+echo
+echo "### $(date) ###"
 repos=( $( grep location /etc/portage/repos.conf/* | cut -d '=' -f2 ) )
 
 # Search for last sync timestamps
 last=0
 text="Checking repositories..."
-echo -e "${green}${text}${normal}" && echo "${text}" >> "${logFile}"
+echo -e "${green}${text}${normal}"
 for i in "${!repos[@]}"; do
 	if [ -f "${repos[$i]}/Manifest" ]; then
 		time[$i]=$( date -d `grep TIMESTAMP "${repos[$i]}/Manifest" | cut -d ' ' -f2` "+%s" )
 		text="Last sync for ${repos[$i]##*/} is `date -d @${time[$i]}`"
-		echo "${text}" >> "${logFile}"
 		[ $QUIET -gt 0 ] && [ $VERBOSE -eq 0 ] || echo "${text}"
 
 		if [ ${time[$i]} -gt `date '+%s'` ]; then
 			text1="Sync date for ${repos[$i]##*/} is newer than now"
 			text2=", please correct your local time"
-			echo "${text1}" >> "${logFile}"
 			[ $X -eq 0 ] &&	echo -e "${red}${text1}${normal}${text2}" || zenity --width=500 --error --title "Time error" --text "<span color=\"red\">${text1}</span>${text2}"
-			echo "Exiting..." | tee -a "${logFile}"
+			echo "Exiting..."
 			exit 1
 		fi
 
 	else
 		text="Unknown last sync for ${repos[$i]##*/}"
-		echo "${text}" >> "${logFile}"
 		[ $VERBOSE -eq 0 ] || echo "${text}"
 	fi
 done
@@ -193,15 +189,15 @@ if [ $now -lt $last ]; then
 		fi
 	fi
 	text="Last sync newer than 24h, "
-	[ $SYNC -eq 0 ] && echo "${text}skipping sync" >> "${logFile}" || echo "${text}forcing sync" >> "${logFile}"
+	[ $SYNC -eq 0 ] && echo "${text}skipping sync" || echo "${text}forcing sync"
 fi
 
 # Sync
 if [ $SYNC -gt 0 ]; then
 	text="Syncing repositories..."
-	echo -e "${green}${text}${normal}" && echo "${text}" >> "${logFile}"
+	echo -e "${green}${text}${normal}"
 	if [ $X -eq 0 ]; then
-		emerge --sync | tee -a "${logFile}"
+		emerge --sync
 		[ $? -gt 0 ] && exit 2
 	else
 		( touch "${tmpFile["zenity"]}" && emerge --sync 2>&1 > "${tmpFile["logs"]}"; rm "${tmpFile["zenity"]}" ) &
@@ -213,18 +209,16 @@ if [ $SYNC -gt 0 ]; then
 		done | zenity --progress --width=500 --title "${text}" --pulsate --auto-close --text ""
 
 		[ $? -gt 0 ] && prepare_for_exit emerge
-		cat "${tmpFile["logs"]}" >> "${logFile}"
+		cat "${tmpFile["logs"]}"
 	fi
 fi
 
 # Upgrade
 text="Checking for upgrades..."
-echo -e "${green}${text}${normal}" && echo "${text}" >> "${logFile}"
+echo -e "${green}${text}${normal}"
 if [ $X -gt 0 ]; then
 	
 	# first check
-	emerge -pquDN ${SET} 2>&1 > "${tmpFile["logs"]}" &
-
 	( touch "${tmpFile["zenity"]}" && emerge -pquDN ${SET} 2>&1 > "${tmpFile["logs"]}"; rm "${tmpFile["zenity"]}" ) &
 	sleep .5
 	dots=""
@@ -236,7 +230,7 @@ if [ $X -gt 0 ]; then
 	done | zenity --progress --width=500 --title "${text}" --pulsate --auto-close --text ""
 
 	[ $? -gt 0 ] && prepare_for_exit emerge && exit 1
-	cat "${tmpFile["logs"]}" >> "${logFile}"
+	cat "${tmpFile["logs"]}"
 
 	if [ ! -s "${tmpFile["logs"]}" ]; then
 		zenity --info --width 500 --title "Upgrade" --text "Your system is already up to date"
@@ -247,20 +241,20 @@ if [ $X -gt 0 ]; then
 		news=`grep "news items need reading" "${tmpFile["logs"]}" | sed 's/*//' `
 		if [ ! "$news" = "" ]; then
 			if zenity --width=500 --question --title "Warning" --text "<span color=\"red\">${news}</span> Do you want to read it now ?" --cancel-label "Non" --ok-label "Oui"; then
-				eselect news read | zenity --text-info --width=500 --height=300 --title "News" | tee -a "${logFile}"
+				eselect news read | zenity --text-info --width=500 --height=300 --title "News"
 			fi
 		fi
 
 		# remove news lines from output & ask
 		sed '/\*/d' "${tmpFile["logs"]}" | zenity --width=500 --height=300 --text-info --title "Here are packages that need updates"
 		if [ "$?" -gt 0 ]; then
-			echo "Aborted" >> "${logFile}"
+			echo "Aborted"
 			prepare_for_exit
 			exit 1
 		fi
 	
 		# finally emerge
-		echo "Ugrading your system" >> "${logFile}"
+		echo "Ugrading your system..."
 		( touch "${tmpFile["zenity"]}" && emerge -quDN ${SET} 2>&1 > "${tmpFile["logs"]}"; rm "${tmpFile["zenity"]}" ) &
 		sleep .5
 		emerging=0		
@@ -283,14 +277,14 @@ if [ $X -gt 0 ]; then
 		done | zenity --progress --width=500 --title "Ugrading your system" --auto-close --text "Calculating upgrade ..."
 
 		[ $? -gt 0 ] && prepare_for_exit emerge && exit 1
-		cat "${tmpFile["logs"]}" >> "${logFile}"
+		cat "${tmpFile["logs"]}"
 	fi
 
 # Standard upgrade
 else
 	[ $QUIET -eq 0 ] && QUIET='' || QUIET='q'
 	[ $VERBOSE -eq 0 ] && VERBOSE='' || VERBOSE='v'
-	emerge -a${QUIET}${VERBOSE}uDN ${SET} | tee -a "${logFile}"
+	emerge -a${QUIET}${VERBOSE}uDN ${SET}
 fi
 
 if [ $? -gt 0 ]; then
@@ -299,14 +293,14 @@ if [ $? -gt 0 ]; then
 	if [ $X -eq 0 ]; then echo -e "${red}${text1}${normal}, ${text2}"
 	else zenity --info --width 500 --title "Error" echo "<span color=\"red\">${text1}</span>, ${text2}"
 	fi
-	echo "${text1}, ${text2}" >> "${logFile}"
+	echo "${text1}, ${text2}"
 	exit 3
 fi
 
 # Depclean
 if [ "$SET" = "@world" ]; then
 	text="Cleaning system..."
-	echo -e "${green}${text}${normal}" && echo "${text}" >> "${logFile}"
+	echo -e "${green}${text}${normal}"
 	if [ $X -gt 0 ]; then
 		
 		# first check
@@ -321,20 +315,20 @@ if [ "$SET" = "@world" ]; then
 		done | zenity --progress --width=500 --title "${text}" --pulsate --auto-close --text ""
 
 		[ $? -gt 0 ] && prepare_for_exit emerge && exit 1
-		cat "${tmpFile["logs"]}" >> "${logFile}"
+		cat "${tmpFile["logs"]}"
 
 		if [ -s "${tmpFile["logs"]}" ]; then
 
 			sed 's/\*//g' "${tmpFile["logs"]}" | zenity --width=500 --height=300 --text-info --title "Here are packages that will be removed"
 			if [ $? -gt 0 ]; then
-				echo "Aborted" >> "${logFile}"
+				echo "Aborted"
 				prepare_for_exit
 				exit 1
 			fi
 		
 			# finally clean
-			text="Cleaning your system"
-			echo "${text}" >> "${logFile}"
+			text="Cleaning your system..."
+			echo "${text}"
 			( touch "${tmpFile["zenity"]}" && emerge -qc 2>&1 > "${tmpFile["logs"]}"; rm "${tmpFile["zenity"]}" ) &
 			sleep .5
 			cleaning=0
@@ -353,18 +347,18 @@ if [ "$SET" = "@world" ]; then
 			done | zenity --progress --width=500 --title "${text}" --auto-close --text ""
 
 			[ $? -gt 0 ] && prepare_for_exit emerge && exit 1
-			cat "${tmpFile["logs"]}" >> "${logFile}"
+			cat "${tmpFile["logs"]}"
 		fi
 
 	# Standard cleaning
 	else
-		emerge -a${QUIET}${VERBOSE}c | tee -a "${logFile}"
+		emerge -a${QUIET}${VERBOSE}c
 	fi
 fi
 
 # Finished
 text="Your system is now up to date"
 [ $X -gt 0 ] && zenity --info --width 500 --title "Upgrade" --text "${text}"
-echo "${text}" >> "${logFile}"
+echo "${text}"
 
 exit 0
